# Import variables
Import('env')

# Source files
src_files = Split('ouranos.cc GLC.cc LS.cc RTQuadrature.cc Parameters.cc '+
  'Geometry.cc FECell.cc TimeDiscretization.cc RadiativeTransfer.cc '+
  'RTMaterialProperties.cc Task.cc')

# Build the program in src
ouranos = env.Program('ouranos',src_files)

# By default build ouranos in src
Default(ouranos)

# Scons install installs ouranos in bin
Alias("install",env.Install('../bin',ouranos))
